import { Entity, PrimaryKey, Property } from '@mikro-orm/decorators/legacy';
import { type EventDateTime } from '@common';

/**
 * Represents a published campus event in the database.
 *
 * Events reach this table via two paths:
 * 1. Auto-published by the ingestion pipeline after a clean submission
 *    (no duplicates found, all validation rules passed)
 * 2. Promoted from the moderation queue after a curator reviews a flagged submission
 *
 * The `datetime` field is stored as `jsonb` to accommodate the
 * {@link EventDateTime} discriminated union without separate columns.
 * MikroORM does not hydrate nested `Date` objects inside JSONB — `datetime.date`
 * and `datetime.startTime` arrive as ISO strings at runtime. Use
 * {@link getComparableDateFromSummary} from the ingestion helpers when you need
 * a reliable `Date` object from this field.
 */
@Entity({ tableName: 'events' })
export class Event {
  /**
   * UUID primary key, generated by PostgreSQL via `uuid_generate_v4()`.
   * Requires the `uuid-ossp` extension on the database.
   */
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id!: string;

  /** Human-readable event title as submitted by the organiser or curator. */
  @Property()
  title!: string;

  /**
   * Structured datetime information stored as JSONB.
   *
   * Shape is either {@link SpecificDateTime} (timed event) or
   * {@link AllDayDate} (full-day event). Narrow on `datetime.type`
   * before accessing shape-specific fields.
   *
   * ⚠️ MikroORM does not hydrate nested `Date` objects from JSONB.
   * Treat `date`, `startTime`, and `endTime` values as `string | Date`
   * at runtime, not guaranteed `Date` instances.
   */
  @Property({ type: 'jsonb' })
  datetime!: EventDateTime;

  /** Venue name as commonly known on campus (e.g. "Trust Hall", "SUB Car Park"). */
  @Property()
  venue!: string;

  /**
   * Optional free-text description shown on the event detail page.
   * May include pricing breakdown, dress code, registration instructions, etc.
   */
  @Property({ nullable: true })
  description?: string;

  /** Timestamp of when this event record was created in the database. */
  @Property({ onCreate: () => new Date() })
  createdAt!: Date;
}
